[general]
working_directory = "~"

[window]
dimensions = { columns = 120, lines =30}
position = { x=300, y=100}
padding = { x = 5, y = 5 }
#startup_mode = "Maximized"
#decorations = "Full"

[font]
size = 12.0
normal = {family = "Hack Nerd Font Mono", style = "Regular"}
bold= {family = "Hack Nerd Font Mono", style = "Bold"}
italic= {family = "Hack Nerd Font Mono", style = "Italic"}


[colors]

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"


[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
    {key = "N", mods = "Control|Shift", action = "SpawnNewInstance"},
    {key = "C", mods = "Control|Shift", action = "Copy"},
    {key = "Q", mods = "Super", action = "Quit"},
    {key = "V", mods = "Control|Shift", action = "Paste"},
]

[terminal]
shell = { program = "/usr/bin/zsh" }
osc52 = "CopyPaste"
